#!/bin/bash

# Maritime Onboarding System - Enhanced Server Setup Script
# Configures the server and starts the application with robust error handling

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'

# Configuration
BUILD_TIMEOUT=300       # 5 minutes max for build
HEALTH_CHECK_TIMEOUT=180 # 3 minutes max for health checks
CORE_SERVICES_TIMEOUT=60 # 1 minute for core services

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
}

warn() {
    echo -e "${YELLOW}[WARNING] $1${NC}"
}

error() {
    echo -e "${RED}[ERROR] $1${NC}"
    cleanup_on_failure
    exit 1
}

info() {
    echo -e "${CYAN}[INFO] $1${NC}"
}

success() {
    echo -e "${GREEN}[SUCCESS] $1${NC}"
}

# Cleanup function for failed deployments
cleanup_on_failure() {
    warn "Deployment failed - cleaning up..."

    # Stop any running containers
    if command -v docker-compose &> /dev/null; then
        docker-compose down --remove-orphans 2>/dev/null || true
    fi

    # Save logs for debugging
    if [ -d "/opt/maritime-onboarding" ]; then
        mkdir -p /opt/maritime-onboarding/failed-deployment-logs
        docker-compose logs > /opt/maritime-onboarding/failed-deployment-logs/docker-logs-$(date +%Y%m%d_%H%M%S).log 2>/dev/null || true
    fi

    warn "Logs saved to /opt/maritime-onboarding/failed-deployment-logs/"
}

# Rollback to previous deployment
rollback_deployment() {
    warn "Initiating rollback to previous deployment..."

    # Stop current deployment
    docker-compose down --remove-orphans

    # Restore from backup if available
    if [ -f "/opt/maritime-onboarding/backups/last-working-deployment.tar.gz" ]; then
        log "Restoring from last working deployment backup..."
        cd /opt/maritime-onboarding
        tar -xzf backups/last-working-deployment.tar.gz
        docker-compose up -d
        success "Rollback completed"
    else
        warn "No backup available for rollback"
    fi
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    error "Please run as root"
fi

log "Starting Maritime Onboarding System server setup..."

# Create application directory structure
log "Creating directory structure..."
mkdir -p /opt/maritime-onboarding/{logs,backups,uploads,certificates}
mkdir -p /var/log/maritime

# Set permissions
chown -R maritime:maritime /opt/maritime-onboarding
chmod -R 755 /opt/maritime-onboarding

# Verify environment file exists (should be generated by deploy script)
log "Verifying environment configuration..."
if [ ! -f .env ]; then
    error "Environment file not found. This should have been generated by the deployment script."
fi

# Validate critical environment variables
if ! grep -q "DB_PASSWORD=" .env || ! grep -q "REDIS_PASSWORD=" .env; then
    error "Critical environment variables missing. Please check the deployment process."
fi

log "Environment configuration verified"

# Install Docker Compose if not present
if ! command -v docker-compose &> /dev/null; then
    log "Installing Docker Compose..."
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
fi

# Create systemd service for automatic startup
log "Creating systemd service..."
cat > /etc/systemd/system/maritime-onboarding.service << 'EOF'
[Unit]
Description=Maritime Onboarding System
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/maritime-onboarding
ExecStart=/usr/local/bin/docker-compose up -d
ExecStop=/usr/local/bin/docker-compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

# Enable the service
systemctl daemon-reload
systemctl enable maritime-onboarding.service

# Create backup script
log "Setting up backup system..."
cat > /opt/maritime-onboarding/backup.sh << 'EOF'
#!/bin/bash

# Maritime Onboarding System Backup Script

BACKUP_DIR="/opt/maritime-onboarding/backups"
DATE=$(date +%Y%m%d_%H%M%S)
RETENTION_DAYS=30

# Create backup directory
mkdir -p $BACKUP_DIR

# Database backup
log "Creating database backup..."
docker-compose exec -T database pg_dump -U postgres maritime_onboarding | gzip > $BACKUP_DIR/db_backup_$DATE.sql.gz

# Application files backup
log "Creating application files backup..."
tar -czf $BACKUP_DIR/app_backup_$DATE.tar.gz uploads certificates logs

# Clean old backups
find $BACKUP_DIR -name "*.gz" -mtime +$RETENTION_DAYS -delete
find $BACKUP_DIR -name "*.tar.gz" -mtime +$RETENTION_DAYS -delete

log "Backup completed: $BACKUP_DIR"
EOF

chmod +x /opt/maritime-onboarding/backup.sh

# Create backup cron job
echo "0 2 * * * root /opt/maritime-onboarding/backup.sh >> /var/log/maritime/backup.log 2>&1" > /etc/cron.d/maritime-backup

# Create log rotation configuration
cat > /etc/logrotate.d/maritime << 'EOF'
/var/log/maritime/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 644 maritime maritime
    postrotate
        docker-compose -f /opt/maritime-onboarding/docker-compose.yml restart app
    endscript
}
EOF

# Build and start the application with Context7 optimizations
log "Building and starting Maritime Onboarding System..."
cd /opt/maritime-onboarding

# Set proper permissions for Docker
chown -R maritime:maritime /opt/maritime-onboarding
chmod +x /opt/maritime-onboarding/backup.sh

# Pull latest base images for faster builds
log "Pulling base images..."
docker-compose pull --ignore-pull-failures

# Build the application with optimizations
log "Building application..."
docker-compose build --no-cache --parallel

# Start core services first (database, redis)
log "Starting core services..."
docker-compose up -d database redis

# Wait for core services to be healthy
log "Waiting for core services to be ready..."
timeout=60
while [ $timeout -gt 0 ]; do
    if docker-compose exec -T database pg_isready -U postgres >/dev/null 2>&1 && \
       docker-compose exec -T redis redis-cli -a "${REDIS_PASSWORD:-}" ping >/dev/null 2>&1; then
        log "Core services are ready!"
        break
    fi
    sleep 2
    timeout=$((timeout - 2))
done

if [ $timeout -le 0 ]; then
    error "Core services failed to start within 60 seconds"
fi

# Start application and nginx
log "Starting application services..."
docker-compose up -d app nginx

# Wait for application to be ready
log "Waiting for application to start..."
timeout=90
while [ $timeout -gt 0 ]; do
    if curl -f http://localhost/health >/dev/null 2>&1; then
        log "Application is ready!"
        break
    fi
    sleep 3
    timeout=$((timeout - 3))
done

if [ $timeout -le 0 ]; then
    warn "Application health check timeout - check logs with: docker-compose logs app"
fi

# Final service status check
log "Checking final service status..."
docker-compose ps

# Run database migrations if available
log "Running database migrations..."
if [ -f "package.json" ] && grep -q "migrate" package.json; then
    docker-compose exec -T app npm run migrate || warn "Migration failed - this is normal for first deployment"
else
    log "No migration script found - skipping database migrations"
fi

# Create initial admin user if needed
log "Setting up initial admin user..."
docker-compose exec -T app node -e "
const fs = require('fs');
const path = require('path');

// Check if we have the necessary dependencies
try {
    const bcrypt = require('bcrypt');
    const { Pool } = require('pg');

    const pool = new Pool({
        connectionString: process.env.DATABASE_URL
    });

    async function createAdmin() {
        try {
            // Check if users table exists
            const tableCheck = await pool.query(
                \"SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'users')\"
            );

            if (!tableCheck.rows[0].exists) {
                console.log('Users table does not exist yet - skipping admin creation');
                return;
            }

            const hashedPassword = await bcrypt.hash('admin123', 10);
            await pool.query(
                'INSERT INTO users (email, password, role, is_active) VALUES (\$1, \$2, \$3, \$4) ON CONFLICT (email) DO NOTHING',
                ['admin@maritime.local', hashedPassword, 'admin', true]
            );
            console.log('✅ Admin user ready: admin@maritime.local / admin123');
        } catch (error) {
            console.log('Admin user setup skipped:', error.message);
        } finally {
            await pool.end();
        }
    }

    createAdmin();
} catch (error) {
    console.log('Admin user creation skipped - dependencies not available:', error.message);
}
" || warn "Admin user creation failed - this is normal if database schema is not ready"

# Display final status and instructions
log "🎉 Maritime Onboarding System deployment completed!"
echo ""
echo -e "${BLUE}=== 📊 Service Status ===${NC}"
docker-compose ps

echo ""
echo -e "${BLUE}=== 🌐 Access Information ===${NC}"
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || echo "YOUR_SERVER_IP")
echo -e "🔗 Application URL: http://$SERVER_IP"
echo -e "👤 Admin Email: admin@maritime.local"
echo -e "🔑 Admin Password: admin123"
echo ""
echo -e "${GREEN}=== 📋 Next Steps ===${NC}"
echo -e "1. 🌍 Configure your domain:"
echo -e "   - Point your domain to: $SERVER_IP"
echo -e "   - Update DOMAIN in .env file"
echo -e "   - Run: docker-compose --profile ssl run --rm certbot"
echo -e ""
echo -e "2. 📧 Configure email settings in .env file:"
echo -e "   - SMTP_HOST, SMTP_USER, SMTP_PASSWORD"
echo -e "   - SECURITY_EMAIL, DEVOPS_EMAIL"
echo -e ""
echo -e "3. 🔒 Security checklist:"
echo -e "   - Change default admin password"
echo -e "   - Review firewall settings"
echo -e "   - Set up regular backups"
echo ""
echo -e "${YELLOW}=== ⚠️  Important Notes ===${NC}"
echo -e "💾 Backup your .env file - it contains generated passwords"
echo -e "📊 Monitor logs: docker-compose logs -f"
echo -e "🏥 Health check: curl http://localhost/health"
echo -e "💰 Estimated monthly cost: ~€11-12 (CX21 + 50GB volume)"
echo ""
echo -e "${GREEN}=== 🛠️  Useful Commands ===${NC}"
echo -e "🔄 Restart services: docker-compose restart"
echo -e "📈 View logs: docker-compose logs -f [service]"
echo -e "🔧 Update app: git pull && docker-compose build && docker-compose up -d"
echo -e "🗄️  Database backup: docker-compose exec database pg_dump -U postgres maritime_onboarding > backup.sql"
